### ISSUE TITLE
Logo & Icon Design

### ISSUE THREAD

**Issue by zularizal** [LeonErath/Pineapple#3]
Hi @LeonErath ,  I'm a graphic designer, after I review your project, I'm interested in your project and I want to contribute by creating a logo/icon for your project. What do you think?

**Comment by LeonErath** [comment]
Hey @zularizal ,

Thank you for your help, but unfortunately the project is not being developed at the moment.

If you still want to design a logo / icon then I will gladly include it in the repository and on the website as well as add you as a contributor.
